// src/app/src/components/character_editor/character_editor.tsx
import { NumberInput, Image, Stack, TextInput, Group, Button, Divider, Loader, Switch } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { useRef, useState } from "react";
import { UploadModal } from "components/upload-modal.tsx";
import { usePromise } from "hooks/promise_hook.ts";
import { Character } from "types/models.ts";
import { parseIntOrUndefined } from "utils.ts";

export interface CharacterEditorProps {
	character: Character
	onSubmit: (character: CharacterEditorResult) => void | Promise<void>;
	uploadStackId?: string
}

export function CharacterEditor({ uploadStackId, character, onSubmit }: CharacterEditorProps) {
	const [submitPromise, setSubmitPromise] = useState<Promise<void>>();
	const [showUploadFile, showFileUploadHandler] = useDisclosure(false);
	
	const stateVars = Object.entries(character)
		.reduce((eState, [key, value]) => {
			const reactProps = useState(value);
			eState[key as EditorKey] = reactProps as any;
			return eState;
		}, {} as CharacterEditorState);
	
	const changedKeys = useRef(new Set<EditorKey>());
	
	const { loading: submitLoading } = usePromise(submitPromise);
	
	function onEdit<K extends EditorKey>(key: K, value: CharacterEditorValue<K>) {
		if (typeof value === 'number' && isNaN(value as any)) {
			(value as any) = null;
		}
		
		console.log(key, value);
		changedKeys.current.add(key);
		stateVars[key][1](value ?? null);
	}
	
	function submit() {
		const toSend = {} as CharacterEditorResult;
		for (const key of changedKeys.current) {
			toSend[key] = stateVars[key][0] as any;
		}
		
		console.log(JSON.stringify(toSend, null, 2));
		const res = onSubmit(toSend);
		if (res instanceof Promise) {
			setSubmitPromise(res);
		}
	}
	
	function wrapNumberValue(val: any): number | string {
		return parseIntOrUndefined(val) ?? '';
	}
	
	function createStateBlock(key: keyof Pick<CharacterEditorCore, 'might' | 'agility' | 'intuition' | 'presence' | 'reason'>) {
		return (
			<NumberInput label={key[0].toUpperCase() + key.slice(1)}
			             value={wrapNumberValue(stateVars[key][0])}
			             onChange={(e) => onEdit(key, parseIntOrUndefined(e) ?? NaN)}/>
		);
	}
	
	return <>
		<UploadModal stackId={uploadStackId}
		             show={showUploadFile}
		             accept=".png,.jpg,.jpeg,.webp"
		             onHide={showFileUploadHandler.close}
		             onComplete={(e) => {
			             onEdit('pictureUrl', `/files/${e}`);
			             showFileUploadHandler.close();
		             }}>
			{(file) => {
				if (file == null) {
					return <></>;
				}
				
				return <Image src={URL.createObjectURL(file)}/>
			}}
		</UploadModal>
		<Stack>
			<TextInput label="Name"
			           value={stateVars['name'][0]}
			           onChange={(e) => onEdit('name', e.target.value)}/>
			<Group>
				{createStateBlock('might')}
				{createStateBlock('agility')}
				{createStateBlock('reason')}
				{createStateBlock('intuition')}
				{createStateBlock('presence')}
			</Group>
			
			<NumberInput label="Victories"
			             value={wrapNumberValue(stateVars['victories'][0])}
			             onChange={(e) => onEdit('victories', parseIntOrUndefined(e) ?? NaN)}/>
			
			<NumberInput label="Max HP"
			             value={wrapNumberValue(stateVars['maxHp'][0])}
			             onChange={(e) => onEdit('maxHp', parseIntOrUndefined(e) ?? NaN)}/>
			
			<NumberInput label="Recoveries"
			             value={wrapNumberValue(stateVars['maxRecoveries'][0])}
			             onChange={(e) => onEdit('maxRecoveries', parseIntOrUndefined(e) ?? NaN)}/>
			
			<TextInput label="Resource Name"
			           value={stateVars['resourceName'][0] ?? ''}
			           onChange={(e) => onEdit('resourceName', e.target.value)}/>
			
			<Switch label={'Offstage'}
			        checked={stateVars['offstage'][0]}
			        onChange={(e) => onEdit('offstage', e.target.checked)}/>
			
			<NumberInput label="Minions"
			             min={0}
			             value={wrapNumberValue(stateVars['minions'][0])}
			             onChange={(e) => onEdit('minions', parseIntOrUndefined(e) ?? 0)}/>
			
			<Divider/>
			{ stateVars['pictureUrl'][0] &&
				<Image src={stateVars['pictureUrl'][0]}></Image>
			}
			<Stack>
				<TextInput label="Picture URL"
				           value={stateVars['pictureUrl'][0] ?? ''}
				           onChange={(e) => onEdit('pictureUrl', e.target.value)}/>
				<Button onClick={showFileUploadHandler.open}>Upload</Button>
			</Stack>
			<Divider my={'md'} />
			<Group justify="end">
				<Button disabled={submitLoading}
				        onClick={submit}
				        leftSection={
					        submitLoading && <Loader/>
				        }>
					Submit
				</Button>
			</Group>
		</Stack>
	</>
}

export type CharacterEditorCore = Omit<Character, 'conditions'>
export type CharacterEditorResult = Partial<CharacterEditorCore>;
type EditorKey = keyof CharacterEditorCore;
type CharacterEditorState = {
	[K in EditorKey]: [CharacterEditorCore[K], (value: CharacterEditorCore[K] | null) => void];
}
type CharacterEditorValue<K extends EditorKey> = CharacterEditorState[K][0];

// packages/web/src/app/features/components/character-editor.component.ts
import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import type { Character } from '../../core/models';
import { parseIntOrUndefined } from '../../core/utils';
import { ButtonComponent } from '../../ui/button.component';
import { UploadModalComponent } from './upload-modal.component';

export type CharacterEditorResult = Partial<Omit<Character, 'conditions'>>;

/** Create/edit form for a character; emits only the fields that changed. */
@Component({
  selector: 'app-character-editor',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ButtonComponent, UploadModalComponent],
  template: `
    <app-upload-modal
      [show]="uploadOpen()"
      [level]="3"
      accept=".png,.jpg,.jpeg,.webp"
      (hide)="uploadOpen.set(false)"
      (complete)="onUpload($event)"
    />
    <div class="flex flex-col gap-3">
      <div>
        <label class="ds-label">Name</label>
        <input class="ds-input" [value]="model().name" (input)="set('name', $any($event.target).value)" />
      </div>
      <div class="grid grid-cols-5 gap-2">
        @for (stat of stats; track stat) {
          <div>
            <label class="ds-label">{{ stat[0].toUpperCase() + stat.slice(1) }}</label>
            <input
              class="ds-input"
              type="number"
              [value]="numValue(stat)"
              (input)="setNum(stat, $any($event.target).value)"
            />
          </div>
        }
      </div>
      <div>
        <label class="ds-label">Victories</label>
        <input class="ds-input" type="number" [value]="numValue('victories')" (input)="setNum('victories', $any($event.target).value)" />
      </div>
      <div>
        <label class="ds-label">Max HP</label>
        <input class="ds-input" type="number" [value]="numValue('maxHp')" (input)="setNum('maxHp', $any($event.target).value)" />
      </div>
      <div>
        <label class="ds-label">Recoveries</label>
        <input class="ds-input" type="number" [value]="numValue('maxRecoveries')" (input)="setNum('maxRecoveries', $any($event.target).value)" />
      </div>
      <div>
        <label class="ds-label">Resource Name</label>
        <input class="ds-input" [value]="model().resourceName ?? ''" (input)="set('resourceName', $any($event.target).value)" />
      </div>
      <label class="flex items-center gap-2">
        <input type="checkbox" class="h-4 w-4 accent-[var(--color-m-blue)]" [checked]="model().offstage" (change)="set('offstage', $any($event.target).checked)" />
        Offstage
      </label>
      <div>
        <label class="ds-label">Minions</label>
        <input class="ds-input" type="number" min="0" [value]="numValue('minions')" (input)="setNum('minions', $any($event.target).value, 0)" />
      </div>
      <hr class="ds-divider" />
      @if (model().pictureUrl) {
        <img class="max-h-48 rounded" [src]="model().pictureUrl" alt="portrait" />
      }
      <div class="flex flex-col gap-2">
        <div>
          <label class="ds-label">Picture URL</label>
          <input class="ds-input" [value]="model().pictureUrl ?? ''" (input)="set('pictureUrl', $any($event.target).value)" />
        </div>
        <app-button (clicked)="uploadOpen.set(true)">Upload</app-button>
      </div>
      <hr class="ds-divider" />
      <div class="flex justify-end">
        <app-button [disabled]="submitting()" (clicked)="submit()">Submit</app-button>
      </div>
    </div>
  `,
})
export class CharacterEditorComponent {
  readonly character = input.required<Character>();
  readonly submitted = output<CharacterEditorResult>();

  protected readonly stats = ['might', 'agility', 'reason', 'intuition', 'presence'] as const;

  readonly model = signal<Character>({} as Character);
  readonly uploadOpen = signal(false);
  readonly submitting = signal(false);
  private readonly changed = new Set<keyof CharacterEditorResult>();
  private initialized = false;

  constructor() {
    queueMicrotask(() => {
      if (!this.initialized) {
        this.initialized = true;
        this.model.set({ ...this.character() });
      }
    });
  }

  numValue(key: keyof Character): number | string {
    const v = this.model()[key];
    return typeof v === 'number' && !Number.isNaN(v) ? v : '';
  }

  set<K extends keyof CharacterEditorResult>(key: K, value: Character[K]): void {
    this.changed.add(key);
    this.model.update((m) => ({ ...m, [key]: value }));
  }

  setNum<K extends keyof CharacterEditorResult>(key: K, raw: string, fallback?: number): void {
    const parsed = parseIntOrUndefined(raw);
    const value = (parsed ?? fallback ?? null) as Character[K];
    this.changed.add(key);
    this.model.update((m) => ({ ...m, [key]: value }));
  }

  onUpload(fileName: string): void {
    this.set('pictureUrl', `/files/${fileName}` as Character['pictureUrl']);
    this.uploadOpen.set(false);
  }

  submit(): void {
    const result: CharacterEditorResult = {};
    for (const key of this.changed) {
      (result as Record<string, unknown>)[key] = this.model()[key as keyof Character];
    }
    this.submitting.set(true);
    this.submitted.emit(result);
  }
}
