// src/app/src/components/character_conditions.tsx
import { faPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { ActionIcon, Autocomplete, Button, FocusTrap, Modal, Pill, Radio, Select, Stack, Text, TextInput } from "@mantine/core";
import { Form } from "@mantine/form";
import { useDisclosure, useInputState } from "@mantine/hooks";
import { modals } from "@mantine/modals";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { FormEvent, FormEventHandler, useCallback, useEffect, useMemo, useRef } from "react";
import { addCharacterCondition, CharacterConditionUpdate, deleteCharacterCondition } from "services/api.ts";
import { Character, CharacterCondition } from "types/models.ts";
import { builder } from "utils.ts";

export interface CharacterConditionsProps {
	character: Character
	mode?: CharacterConditionMode
}

type CharacterConditionMode = 'button' | 'list' | 'all';

export function CharacterConditions({ character, mode }: CharacterConditionsProps) {
	const [showModal, modalHandles] = useDisclosure(false);
	const openModals = useRef(new Set<string>());
	
	const queryClient = useQueryClient();
	
	function closeAllModals() {
		openModals.current.forEach((modal) => {
			modals.close(modal);
		});
		openModals.current.clear();
	}
	
	useEffect(() => {
		return () => {
			closeAllModals();
		}
	}, []);
	
	const createConditionMutation = useMutation({
		mutationFn: (condition: CharacterConditionUpdate) => {
			return addCharacterCondition(condition);
		},
		onSuccess: async () => {
			await queryClient.invalidateQueries({ queryKey: ['character', character.id] });
			modalHandles.close();
		}
	});
	
	const deleteConditionMutation = useMutation({
		mutationFn: (id: number) => {
			return deleteCharacterCondition(id);
		},
		onSuccess: async () => {
			await queryClient.invalidateQueries({ queryKey: ['character', character.id] });
			closeAllModals();
		}
	});
	
	const deleteCallback = useCallback((condition: CharacterCondition) => {
		const id = modals.openConfirmModal({
			title: 'Remove Condition',
			children: `Are you sure you want to remove ${condition?.name} from ${character.name}?`,
			confirmProps: {
				color: 'red',
				children: 'Remove',
				...{
					'data-autofocus': true
				} as any
			},
			cancelProps: {
				children: 'Cancel'
			},
			onConfirm: () => {
				deleteConditionMutation.mutate(condition.id);
			},
		});
		
		openModals.current.add(id);
	}, [deleteConditionMutation, character.name]);
	
	const buttonView = useMemo(() => {
		return <>
			<ActionIcon onClick={modalHandles.open}>
				<FontAwesomeIcon icon={faPlus} />
			</ActionIcon>
		</>;
	}, []);
	
	const listView = useMemo(() => {
		return <>
			<Pill.Group>
				{character.conditions.map((c) => {
					return <Pill key={c.id} c={'blue'} size={'md'} onRemove={() => deleteCallback(c)} withRemoveButton>{c.name}</Pill>
				})}
			</Pill.Group>
		</>;
	}, [character.conditions]);
	
	return <>
		<Modal title={'Add Condition'} opened={showModal} onClose={modalHandles.close} trapFocus>
			<ConditionEditor character={character.id} onSubmit={createConditionMutation.mutate} />
		</Modal>
		{
			builder(() => {
				switch (mode ?? 'all') {
					case 'button':
						return buttonView;
					case 'list':
						return listView;
					case 'all':
						return <>
							{buttonView}
							{listView}
						</>;
					default:
						return null;
				}
			})
		}
	</>
}

interface ConditionEditorProps {
	character: number,
	onSubmit: (condition: CharacterConditionUpdate) => void
}

function ConditionEditor({ character, onSubmit }: ConditionEditorProps) {
	const [name, setName] = useInputState<string>('');
	const [type, setType] = useInputState<CharacterConditionUpdate['endType'] | string>('save');
	
	const disabled = !name || (type != 'endOfTurn' && type != 'save');
	
	const submitCallback = useCallback((event: FormEvent) => {
		onSubmit({ name, character, endType: type as any });
		
		event.preventDefault();
	}, [onSubmit, name, character, type]);
	
	return (
		<form onSubmit={submitCallback}>
			<FocusTrap>
				<Stack>
					<Autocomplete data={conditionOptions} data-autofocus label="Name" value={name} onChange={setName}></Autocomplete>
					<Radio.Group label={'End Type'}
					             value={type}
					             onChange={setType}>
						<Radio mt={'xs'} value={'save'} label={'Save'}></Radio>
						<Radio mt={'xs'} value={'endOfTurn'} label={'End of Turn'}></Radio>
					</Radio.Group>
					<Button type={'submit'} disabled={disabled}>Submit</Button>
				</Stack>
			</FocusTrap>
		</form>
	);
}

const conditionOptions = [
	'Bleeding',
	'Dazed',
	'Frightened',
	'Grabbed',
	'Prone',
	'Restrained',
	'Slowed',
	'Taunted',
	'Weakened'
];

// packages/web/src/app/features/components/character-conditions.component.ts
import { ChangeDetectionStrategy, Component, inject, input, signal } from '@angular/core';
import { faPlus } from '@fortawesome/free-solid-svg-icons';
import type { Character, CharacterCondition } from '../../core/models';
import { ApiService } from '../../core/api.service';
import { CampaignStore } from '../../core/campaign-store.service';
import { ActionIconComponent } from '../../ui/action-icon.component';
import { ButtonComponent } from '../../ui/button.component';
import { IconComponent } from '../../ui/icon.component';
import { ModalComponent } from '../../ui/modal.component';

type Mode = 'button' | 'list' | 'all';

/** Add/remove conditions on a character (Mantine CharacterConditions). */
@Component({
  selector: 'app-character-conditions',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ActionIconComponent, ButtonComponent, IconComponent, ModalComponent],
  template: `
    @if (mode() === 'button' || mode() === 'all') {
      <app-action-icon (clicked)="addOpen.set(true)"><app-icon [name]="plus" /></app-action-icon>
    }
    @if (mode() === 'list' || mode() === 'all') {
      <div class="flex flex-wrap gap-1">
        @for (c of character().conditions; track c.id) {
          <span
            class="inline-flex items-center gap-1 rounded-full bg-m-dark-5 px-2 py-0.5 text-sm text-m-blue-light"
          >
            {{ c.name }}
            <button class="text-m-dark-1 hover:text-m-red" (click)="confirmRemove(c)">×</button>
          </span>
        }
      </div>
    }

    <app-modal title="Add Condition" [opened]="addOpen()" (closed)="addOpen.set(false)">
      <form class="flex flex-col gap-3" (submit)="submit($event)">
        <div>
          <label class="ds-label">Name</label>
          <input class="ds-input" list="condition-options" [value]="name()" (input)="name.set($any($event.target).value)" />
          <datalist id="condition-options">
            @for (opt of options; track opt) {
              <option [value]="opt"></option>
            }
          </datalist>
        </div>
        <div>
          <label class="ds-label">End Type</label>
          <label class="mt-1 flex items-center gap-2">
            <input type="radio" name="endType" value="save" [checked]="endType() === 'save'" (change)="endType.set('save')" />
            Save
          </label>
          <label class="mt-1 flex items-center gap-2">
            <input type="radio" name="endType" value="endOfTurn" [checked]="endType() === 'endOfTurn'" (change)="endType.set('endOfTurn')" />
            End of Turn
          </label>
        </div>
        <app-button [disabled]="!name()" (clicked)="submit($event)">Submit</app-button>
      </form>
    </app-modal>

    <app-modal title="Remove Condition" [opened]="toRemove() != null" (closed)="toRemove.set(null)">
      <p>Are you sure you want to remove {{ toRemove()?.name }} from {{ character().name }}?</p>
      <hr class="ds-divider" />
      <div class="flex justify-end gap-2">
        <app-button color="gray" (clicked)="toRemove.set(null)">Cancel</app-button>
        <app-button color="red" (clicked)="remove()">Remove</app-button>
      </div>
    </app-modal>
  `,
})
export class CharacterConditionsComponent {
  private readonly api = inject(ApiService);
  private readonly store = inject(CampaignStore);
  readonly character = input.required<Character>();
  readonly mode = input<Mode>('all');

  protected readonly plus = faPlus;
  protected readonly options = [
    'Bleeding',
    'Dazed',
    'Frightened',
    'Grabbed',
    'Prone',
    'Restrained',
    'Slowed',
    'Taunted',
    'Weakened',
  ];

  readonly addOpen = signal(false);
  readonly name = signal('');
  readonly endType = signal<'save' | 'endOfTurn'>('save');
  readonly toRemove = signal<CharacterCondition | null>(null);

  async submit(event: Event): Promise<void> {
    event.preventDefault();
    if (!this.name()) return;
    await this.api.addCharacterCondition({
      name: this.name(),
      character: this.character().id,
      endType: this.endType(),
    });
    this.store.refetchCharacter(this.character().id);
    this.addOpen.set(false);
    this.name.set('');
    this.endType.set('save');
  }

  confirmRemove(condition: CharacterCondition): void {
    this.toRemove.set(condition);
  }

  async remove(): Promise<void> {
    const condition = this.toRemove();
    if (!condition) return;
    await this.api.deleteCharacterCondition(condition.id);
    this.store.refetchCharacter(this.character().id);
    this.toRemove.set(null);
  }
}
