// packages/web/src/app/features/campaign-detail/campaign-detail.component.ts
import { ChangeDetectionStrategy, Component, computed, effect, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { faBook, faBriefcase, faImage, faPlus } from '@fortawesome/free-solid-svg-icons';
import type { Character, Combat } from '../../core/models';
import { emptyCharacter } from '../../core/models';
import { ApiService } from '../../core/api.service';
import { CampaignStore } from '../../core/campaign-store.service';
import { CampaignBackgroundService } from '../../core/campaign-background.service';
import { ErrorService } from '../../core/error.service';
import { ActionIconComponent } from '../../ui/action-icon.component';
import { ButtonComponent } from '../../ui/button.component';
import { CardComponent } from '../../ui/card.component';
import { IconComponent } from '../../ui/icon.component';
import { ModalComponent } from '../../ui/modal.component';
import { CharacterCardComponent } from '../components/character-card.component';
import { CharacterEditorComponent, type CharacterEditorResult } from '../components/character-editor.component';
import { CharacterSelectorComponent, type CharacterSelection } from '../components/character-selector.component';
import { InventoryListComponent } from '../components/inventory-list.component';
import { UploadModalComponent } from '../components/upload-modal.component';

/** Campaign hub: combats, character roster, background, and display link. */
@Component({
  selector: 'app-campaign-detail',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ActionIconComponent,
    ButtonComponent,
    CardComponent,
    IconComponent,
    ModalComponent,
    CharacterCardComponent,
    CharacterEditorComponent,
    CharacterSelectorComponent,
    InventoryListComponent,
    UploadModalComponent,
  ],
  template: `
    @if (campaign(); as details) {
      <div class="flex flex-col gap-4 p-3">
        <div>
          <div class="glass left-anchored inline-flex w-fit items-center gap-2 p-3">
            <h2 class="text-xl font-bold">{{ details.campaign.name }}</h2>
            <app-action-icon variant="outline" (clicked)="goToDisplay()"><app-icon [name]="book" /></app-action-icon>
            <app-action-icon variant="outline" (clicked)="backgroundUploadOpen.set(true)"><app-icon [name]="image" /></app-action-icon>
          </div>
        </div>

        <!-- Combats -->
        <div class="flex flex-col gap-2">
          <div class="glass left-anchored inline-flex w-fit items-center gap-2 p-3">
            <h3 class="text-lg font-bold">Combats</h3>
            <app-action-icon (clicked)="newCombatOpen.set(true)"><app-icon [name]="plus" /></app-action-icon>
          </div>
          <div class="flex flex-wrap gap-2">
            @for (combat of combats(); track combat.id) {
              <app-card class="w-1/2">
                <div class="flex justify-between">
                  <h3 class="text-lg font-bold">Round: {{ combat.round }}</h3>
                  <div class="flex flex-col gap-1">
                    <app-button (clicked)="viewCombat(combat)">View</app-button>
                    <app-button color="red" (clicked)="combatToDelete.set(combat)">Delete</app-button>
                  </div>
                </div>
              </app-card>
            }
          </div>
        </div>

        <!-- Characters -->
        <div class="flex flex-col gap-2">
          <div class="glass left-anchored inline-flex w-fit items-center gap-2 p-3">
            <h3 class="text-lg font-bold">Characters</h3>
            <app-action-icon (clicked)="newCharacterOpen.set(true)"><app-icon [name]="plus" /></app-action-icon>
          </div>
          <div class="flex flex-wrap items-start gap-2">
            @for (column of characterColumns(); track $index) {
              <div class="flex flex-col gap-2">
                @for (character of column; track character.id) {
                  <app-character-card [character]="character" type="tile" (portraitClick)="viewCharacter(character)">
                    <div cardRight class="flex-shrink">
                      <app-action-icon (clicked)="inventoryCharacterId.set(character.id)"><app-icon [name]="briefcase" /></app-action-icon>
                    </div>
                  </app-character-card>
                }
              </div>
            }
          </div>
        </div>
      </div>

      <!-- Inventory modal -->
      <app-modal
        [opened]="inventoryCharacter() != null"
        [title]="'Inventory for ' + (inventoryCharacter()?.name ?? '')"
        (closed)="inventoryCharacterId.set(null)"
      >
        @if (inventoryCharacter(); as ic) {
          <app-inventory-list [characterId]="ic.id" [items]="ic.inventory" />
        }
      </app-modal>

      <!-- New character modal -->
      <app-modal title="New Character" [opened]="newCharacterOpen()" (closed)="newCharacterOpen.set(false)">
        @if (newCharacterOpen()) {
          <app-character-editor [character]="blankCharacter" (submitted)="createCharacter($event)" />
        }
      </app-modal>

      <!-- New combat modal -->
      <app-modal title="New Combat" [opened]="newCombatOpen()" (closed)="newCombatOpen.set(false)">
        <div class="flex flex-col gap-3">
          <app-character-selector [characters]="details.characters" (changed)="combatSelection.set($event)" />
          <hr class="ds-divider" />
          <div class="flex justify-end gap-2">
            <app-button color="gray" (clicked)="newCombatOpen.set(false)">Cancel</app-button>
            <app-button [disabled]="creatingCombat()" (clicked)="createCombat()">Create</app-button>
          </div>
        </div>
      </app-modal>

      <!-- Delete combat modal -->
      <app-modal title="Delete Combat" [opened]="combatToDelete() != null" (closed)="combatToDelete.set(null)">
        <div class="flex flex-col gap-3">
          <span>Are you sure you want to delete this combat?</span>
          <hr class="ds-divider" />
          <div class="flex justify-end gap-2">
            <app-button color="gray" (clicked)="combatToDelete.set(null)">Cancel</app-button>
            <app-button color="red" (clicked)="deleteCombat()">Delete</app-button>
          </div>
        </div>
      </app-modal>

      <!-- Background upload -->
      <app-upload-modal
        [show]="backgroundUploadOpen()"
        accept=".png,.jpg,.jpeg,.webp"
        (hide)="backgroundUploadOpen.set(false)"
        (complete)="setBackground($event)"
      />
    }
  `,
})
export class CampaignDetailComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly api = inject(ApiService);
  private readonly store = inject(CampaignStore);
  private readonly background = inject(CampaignBackgroundService);
  private readonly errors = inject(ErrorService);

  protected readonly book = faBook;
  protected readonly image = faImage;
  protected readonly plus = faPlus;
  protected readonly briefcase = faBriefcase;
  protected readonly blankCharacter = emptyCharacter();

  private readonly params = toSignal(this.route.paramMap, { requireSync: true });
  private readonly id = computed(() => Number.parseInt(this.params().get('id') ?? '', 10));

  protected readonly campaign = computed(() => {
    const id = this.id();
    if (Number.isNaN(id)) return undefined;
    return this.store.campaign(id)();
  });
  protected readonly combats = computed(() => {
    const id = this.id();
    if (Number.isNaN(id)) return undefined;
    return this.store.combatsFor(id)();
  });

  protected readonly characterColumns = computed(() => {
    const chars = (this.campaign()?.characters ?? []).filter((c) => !c.offstage);
    const columns: Character[][] = [];
    chars.forEach((character, index) => {
      if (index % 5 === 0) columns.push([character]);
      else columns[columns.length - 1].push(character);
    });
    return columns;
  });

  readonly newCharacterOpen = signal(false);
  readonly newCombatOpen = signal(false);
  readonly combatToDelete = signal<Combat | null>(null);
  readonly backgroundUploadOpen = signal(false);
  readonly inventoryCharacterId = signal<number | null>(null);
  readonly combatSelection = signal<CharacterSelection>({});
  readonly creatingCombat = signal(false);

  protected readonly inventoryCharacter = computed(() => {
    const id = this.inventoryCharacterId();
    if (id == null) return null;
    return this.campaign()?.characters.find((c) => c.id === id) ?? null;
  });

  constructor() {
    if (Number.isNaN(this.id())) void this.router.navigate(['/']);
    effect(() => this.background.apply(this.campaign()?.campaign));
  }

  goToDisplay(): void {
    void this.router.navigate(['/campaigns', this.id(), 'display']);
  }
  viewCombat(combat: Combat): void {
    void this.router.navigate(['/combats', combat.id]);
  }
  viewCharacter(character: Character): void {
    void this.router.navigate(['/characters', character.id]);
  }

  async createCharacter(result: CharacterEditorResult): Promise<void> {
    try {
      await this.api.createCharacter({ ...result, campaign: this.id(), user: 1 });
      this.store.refetchCampaign(this.id());
      this.newCharacterOpen.set(false);
    } catch (err) {
      this.errors.set(err);
    }
  }

  async createCombat(): Promise<void> {
    this.creatingCombat.set(true);
    try {
      const characters = Object.entries(this.combatSelection())
        .filter(([, v]) => v)
        .map(([k]) => Number.parseInt(k, 10));
      const combat = await this.api.createCombat({ campaign: this.id(), characters });
      this.store.refetchCombats(this.id());
      this.newCombatOpen.set(false);
      void this.router.navigate(['/combats', combat.id]);
    } finally {
      this.creatingCombat.set(false);
    }
  }

  async deleteCombat(): Promise<void> {
    const combat = this.combatToDelete();
    if (!combat) return;
    await this.api.deleteCombat(combat.id);
    this.store.refetchCombats(this.id());
    this.combatToDelete.set(null);
  }

  async setBackground(fileName: string): Promise<void> {
    await this.api.updateCampaign(this.id(), { background: `/files/${fileName}` });
    this.store.refetchCampaign(this.id());
    this.backgroundUploadOpen.set(false);
  }
}

// src/app/src/routes/campaign_detail/page.tsx
import { faBook, faImage, faPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Fragment, useContext, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Anchored } from "components/anchored.tsx";
import { CharacterSelector } from "components/character_selector/character_selector.tsx";
import { UploadModal } from "components/upload-modal.tsx";
import { useCampaign, useCombatsForCampaign, useWatchCampaign } from "hooks/api_hooks.ts";
import { CharacterCard } from "components/character_card/card.tsx";
import { CharacterEditor } from "components/character_editor/character_editor.tsx";
import { createCharacter, createCombat, CreateCombatUpdate, deleteCombat, updateCampaign } from "services/api.ts";
import { ErrorContext } from "services/contexts.ts";
import { Character, Combat } from "types/models.ts";
import { ActionIcon, Button, Card, Flex, Modal, Image, Title, Stack, Group, Divider, useModalsStack } from "@mantine/core";
import Element = React.JSX.Element;

export function CampaignDetail() {
	const queryClient = useQueryClient();
	
	const stack = useModalsStack(['character-editor', 'upload-modal']);
	
	const [newCharacter, setNewCharacter] = useState(false);
	const [newCombat, setNewCombat] = useState(false);
	const [combatToDelete, setCombatToDelete] = useState<Combat | null>(null);
	
	const [showBackgroundUpload, setShowBackgroundUpload] = useState(false);
	
	const combatSelected = useRef<Record<number, boolean>>({});
	
	const [_, setError] = useContext(ErrorContext);
	
	const params = useParams();
	const navigate = useNavigate();
	const id = parseInt(params.id as string);
	if (isNaN(id) || id == null) {
		console.error(`Invalid campaign ${id}`);
		navigate('/');
		return <></>;
	}
	
	useWatchCampaign(id);
	const { data: campaign } = useCampaign(id);
	const { data: combats } = useCombatsForCampaign(campaign?.campaign.id);
	
	const updateCampaignBackgroundMutation = useMutation({
		mutationFn: (url?: string) => {
			return updateCampaign(id, { background: url });
		},
		onSuccess: async () => {
			await queryClient.invalidateQueries({
				queryKey: ['campaign', id]
			});
			setShowBackgroundUpload(false);
		},
	});
	
	const deleteCombatMutation = useMutation({
		mutationFn: (id: number) => {
			return deleteCombat(id);
		},
		onSuccess: async () => {
			await queryClient.invalidateQueries({
				queryKey: ['combat', id]
			});
			
			await queryClient.invalidateQueries({
				queryKey: ['combats', id]
			});
			
			setCombatToDelete(null);
		}
	});
	
	const saveCharacterMutation = useMutation({
		mutationFn: (character: Partial<Character>) => {
			character.campaign = id;
			character.user = 1;
			
			return createCharacter(character);
		},
		onSuccess: async () => {
			await queryClient.invalidateQueries({
				queryKey: ['campaign', id]
			});
			
			setNewCharacter(false);
		},
		onError: setError
	})
	
	const createCombatMutation = useMutation({
		mutationFn: (update: CreateCombatUpdate) => {
			return createCombat(update);
		},
		onSuccess: async (data) => {
			setNewCombat(false);
			await queryClient.invalidateQueries({
				queryKey: ['combats', id]
			});
			
			navigate(`/combats/${data.id}`);
		},
	});
	
	
	
	const newCharacterModal = useMemo(() => {
		const model = Character.new();
		
		return (
			<Modal.Stack>
				<Modal stackId={'character-editor'} opened={newCharacter} title={'New Character'} onClose={() => setNewCharacter(false)}>
					<CharacterEditor uploadStackId={'upload-modal'} character={model} onSubmit={saveCharacterMutation.mutateAsync}></CharacterEditor>
				</Modal>
			</Modal.Stack>
		);
	}, [newCharacter, saveCharacterMutation.mutateAsync]);
	
	const newCombatModal = useMemo(() => {
		if (!campaign) {
			return <></>;
		}
		
		const onCreate = () => {
			const selected = Object.entries(combatSelected.current)
				.filter(([, value]) => value)
				.map(([key]) => parseInt(key));
			
			createCombatMutation.mutate({
				campaign: campaign.campaign.id,
				characters: selected
			});
		}
		
		return <>
			<Modal title={'New Combat'}
				     opened={newCombat}
			       onEnterTransitionEnd={() => combatSelected.current = {}}
			       onClose={() => setNewCombat(false)}>
				<Stack>
					<div>
						<CharacterSelector onChange={(e) => combatSelected.current = e}
						                   characters={campaign.characters}/>
					</div>
					
					<Divider my={2}/>
					<Group justify={'end'}>
						<Button color="gray" onClick={() => setNewCombat(false)}>Cancel</Button>
						<Button disabled={createCombatMutation.isPending} onClick={() => onCreate()}>Create</Button>
					</Group>
				</Stack>
				
			</Modal>
		</>;
	}, [campaign, newCombat, createCombatMutation]);
	
	const deleteCombatModal = useMemo(() => {
		return <>
			<Modal title={'Delete Combat'}
			       opened={!!combatToDelete}
			       onClose={() => setCombatToDelete(null)}>
				<Stack>
					Are you sure you want to delete this combat?
					<Divider my={2}/>
					<Group justify={'end'}>
						<Button color="gray" onClick={() => setCombatToDelete(null)}>Cancel</Button>
						<Button color="red" onClick={() => {
							if (combatToDelete) {
								deleteCombatMutation.mutate(combatToDelete.id);
							}
						}}>Delete</Button>
					</Group>
				</Stack>
			</Modal>
		</>
	}, [combatToDelete, deleteCombatMutation]);
	
	const combatElements = useMemo(() => {
		return <>
			<Stack>
				<Anchored position={'left'}>
					<Title display={'inline-block'} pr={8} order={3}>Combats</Title>
					<ActionIcon onClick={() => setNewCombat(true)}>
						<FontAwesomeIcon icon={faPlus}/>
					</ActionIcon>
				</Anchored>
				<Flex>
					{combats?.map((combat) => {
						return (
							<Fragment key={combat.id}>
								<Card w={'50%'}>
									<Flex justify={'space-between'} m={2}>
										<Title order={3}>
											Round: {combat.round}
										</Title>
										<Flex direction={'column'} justify={'center'}>
											<Button mb={2} onClick={() => navigate(`/combats/${combat.id}`)}>
												View
											</Button>
											<Button color="red" onClick={() => setCombatToDelete(combat)}>
												Delete
											</Button>
										</Flex>
									</Flex>
								</Card>
							</Fragment>
						)
					})}
				</Flex>
			</Stack>
		</>;
	}, [combats, navigate]);
	
	const characterElements = useMemo(() => {
		return campaign && campaign.characters.reduce((acc, character, index) => {
			if (character.offstage) {
				return acc;
			}
			
			const characterEl = (
				<CharacterCard onPortraitClick={() => navigate(`/characters/${character.id}`)} key={character.id} character={character} type={'tile'}/>
			)
			
			if (index % 5 == 0) {
				acc.push([characterEl]);
			}
			else {
				acc[acc.length - 1].push(characterEl);
			}
			
			return acc;
		}, new Array<Element[]>())
			.map((row, index) => (
				<Stack key={index}>
					{row.map((el) => (el))}
				</Stack>
			));
	}, [campaign, navigate]);
	
	const campaignDisplay = useMemo(() => (
		campaign &&
	    <Stack>
	      <Flex flex={1}>
          <Anchored position={'left'}>
	          <Group>
	            <Title display={'inline-block'} pr={8} order={2}>{campaign.campaign.name}</Title>
		          <ActionIcon variant={'outline'} onClick={() => navigate(`/campaigns/${campaign.campaign.id}/display`)}>
			          <FontAwesomeIcon icon={faBook} />
		          </ActionIcon>
		          <ActionIcon variant={'outline'} onClick={() => setShowBackgroundUpload(true)}>
				          <FontAwesomeIcon icon={faImage} />
		          </ActionIcon>
	          </Group>
          </Anchored>
	      </Flex>
	      {combatElements}
	      <Stack flex={3}>
		      <Anchored position={'left'}>
			      <Title display={'inline-block'} pr={8} order={3}>Characters</Title>
			      <ActionIcon onClick={() => setNewCharacter(true)}>
					      <FontAwesomeIcon icon={faPlus} />
			      </ActionIcon>
		      </Anchored>
          <Group align={'start'}>
						{characterElements?.map((row) => (
							row
						))}
          </Group>
	      </Stack>
	    </Stack>
	), [campaign, characterElements, combatElements, navigate]);
	
	if (campaign) {
		return (
			<>
				<UploadModal show={showBackgroundUpload}
				             accept=".png,.jpg,.jpeg,.webp"
				             onHide={() => setShowBackgroundUpload(false)}
				             onComplete={(e) => updateCampaignBackgroundMutation.mutate(e ? `/files/${e}` : undefined)}>
					{(file) => {
						if (file == null) return <></>;
						return <Image fit={'contain'} src={URL.createObjectURL(file)}/>;
					}}
				</UploadModal>
				{deleteCombatModal}
				{newCombatModal}
				{newCharacterModal}
				{campaignDisplay}
			</>
		);
	}
}
