// packages/web/src/app/features/components/upload-modal.component.ts
import { ChangeDetectionStrategy, Component, inject, input, output, signal } from '@angular/core';
import { ApiService } from '../../core/api.service';
import { ButtonComponent } from '../../ui/button.component';
import { ModalComponent } from '../../ui/modal.component';

/** Upload a file with an image preview (Mantine UploadModal). */
@Component({
  selector: 'app-upload-modal',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ButtonComponent, ModalComponent],
  template: `
    <app-modal [opened]="show()" [level]="level()" title="Upload" (closed)="onClose()">
      <div class="flex flex-col items-center gap-3">
        @if (previewUrl()) {
          <img class="max-h-64 rounded" [src]="previewUrl()" alt="preview" />
        }
        @if (file()) {
          <span class="text-sm text-m-dark-1">{{ file()!.name }}</span>
        }
        <label class="ds-btn cursor-pointer">
          Select File
          <input type="file" class="hidden" [accept]="accept()" (change)="onFileChange($event)" />
        </label>
      </div>
      <hr class="ds-divider" />
      <div class="flex justify-end">
        <app-button [disabled]="pending() || file() == null" (clicked)="upload()">Upload</app-button>
      </div>
    </app-modal>
  `,
})
export class UploadModalComponent {
  private readonly api = inject(ApiService);
  readonly show = input(false);
  readonly accept = input<string>('');
  readonly level = input(1);
  readonly hide = output<void>();
  readonly complete = output<string>();

  readonly file = signal<File | null>(null);
  readonly previewUrl = signal<string | null>(null);
  readonly pending = signal(false);

  onFileChange(event: Event): void {
    const selected = (event.target as HTMLInputElement).files?.item(0) ?? null;
    this.setFile(selected);
  }

  private setFile(selected: File | null): void {
    this.file.set(selected);
    this.previewUrl.set(selected ? URL.createObjectURL(selected) : null);
  }

  onClose(): void {
    this.setFile(null);
    this.hide.emit();
  }

  async upload(): Promise<void> {
    const selected = this.file();
    if (!selected) return;
    this.pending.set(true);
    try {
      const result = await this.api.uploadFile(selected);
      this.complete.emit(result.fileName);
      this.setFile(null);
    } finally {
      this.pending.set(false);
    }
  }
}

// src/app/src/components/upload-modal.tsx
import { Button, Divider, FileButton, Group, Modal, useModalsStack } from "@mantine/core";
import { useMutation } from "@tanstack/react-query";
import { ReactElement, useId, useRef, useState } from "react";
import { uploadFile } from "services/api.ts";

export interface UploadModalProps {
	stackId?: string;
	show: boolean;
	onHide?: () => void;
	accept?: string;
	children?: (file: File | null) => ReactElement;
	onComplete?: (fileName: string) => void;
}

export function UploadModal({ stackId, onComplete, onHide, show, accept, children }: UploadModalProps) {
	const [file, setFile] = useState<File | null>(null);
	const inputRef = useRef<HTMLInputElement>(null);
	
	const uploadMutation = useMutation({
		mutationFn: async () => {
			if (file == null) {
				throw new Error('No file selected');
			}
			
			return uploadFile(file);
		},
		onSuccess: (data) => {
			onComplete?.(data.fileName);
		}
	});
	
	const submitDisabled = uploadMutation.isPending || file == null;
	
	function onClose() {
		setFile(null);
		onHide?.();
	}
	
	function onFileChange() {
		const input = inputRef.current;
		if (input == null) {
			setFile(null);
			return;
		}
		
		const file = input.files?.item(0)
		setFile(file ?? null);
	}
	
	return <>
		<Modal stackId={stackId} title={'Upload'} opened={show} onClose={onClose}>
			<input accept={accept} onChange={() => onFileChange()} className="d-none" ref={inputRef} type="file"/>
			<div className="d-flex flex-column justify-content-center align-items-center">
				{children?.(file)}
				{
					file &&
						<label>{file?.name}</label>
				}
				<FileButton onChange={(e) => setFile(e)}>
					{(props) => {
						return <>
							<Button {...props}>Select File</Button>
						</>
					}}
				</FileButton>
			</div>
			<Divider my="md"/>
			<Group justify="end">
				<Button onClick={() => uploadMutation.mutate()} disabled={submitDisabled} className="btn btn-primary">Upload</Button>
			</Group>
		</Modal>
	</>;
}
